version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - run: npm install
      - run: CI=false npm run build
  # install-packages:
  #   docker:
  #     - image: 'cimg/base:stable'
  #   steps:
  #     - checkout
  #     - run: npm install
  # build:
  #   docker:
  #     - image: 'cimg/base:stable'
  #   steps:
  #     - checkout
  #     - run: npm run build
workflows:
  test_my_app:
    jobs:
      - install-node-example
      # - install-packages
      # - build
